# -*- coding: utf-8 -*-
"""cat dog classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nps4BO3dHXK8fwup3429EQuaI8p9m06S
"""

#importing the necessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import joblib

# Create synthetic dataset
np.random.seed(0)
head_size = np.random.normal(30, 5, 100)  # Head size in cm
body_length = np.random.normal(50, 10, 100)  # Body length in cm
labels = np.random.choice([0, 1], 100)  # 0 for cat, 1 for dog

# Combine into a DataFrame
data = pd.DataFrame({
    'head_size': head_size,
    'body_length': body_length,
    'label': labels
})

# Train logistic regression model
X = data[['head_size', 'body_length']]
y = data['label']
model = LogisticRegression()
model.fit(X, y)

# Save the model
joblib.dump(model, 'cat_dog_classification_model.pkl')

